# Form implementation generated from reading ui file 'c:\Users\aky547\GitHub\Semesterapparate\ui\setupwizard.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(640, 480)
        Wizard.setMaximumSize(QtCore.QSize(640, 480))
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.textBrowser = QtWidgets.QTextBrowser(self.wizardPage1)
        self.textBrowser.setGeometry(QtCore.QRect(200, 10, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.label = QtWidgets.QLabel(self.wizardPage2)
        self.label.setGeometry(QtCore.QRect(10, 0, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.wizardPage2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.default_apps = QtWidgets.QCheckBox(self.wizardPage2)
        self.default_apps.setGeometry(QtCore.QRect(100, 40, 70, 17))
        self.default_apps.setText("")
        self.default_apps.setObjectName("default_apps")
        self.label_3 = QtWidgets.QLabel(self.wizardPage2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_3.setObjectName("label_3")
        self.custom_applications = QtWidgets.QFrame(self.wizardPage2)
        self.custom_applications.setGeometry(QtCore.QRect(280, 10, 331, 361))
        self.custom_applications.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.custom_applications.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.custom_applications.setObjectName("custom_applications")
        self.save_path = QtWidgets.QLineEdit(self.wizardPage2)
        self.save_path.setGeometry(QtCore.QRect(80, 70, 113, 20))
        self.save_path.setObjectName("save_path")
        self.btn_save_path_select = QtWidgets.QToolButton(self.wizardPage2)
        self.btn_save_path_select.setGeometry(QtCore.QRect(200, 70, 25, 19))
        self.btn_save_path_select.setObjectName("btn_save_path_select")
        Wizard.addPage(self.wizardPage2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.textBrowser.setHtml(_translate("Wizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Setup für das Semesterapparatsprogram.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Im Anschluss werden wichtige Einstellungen gesetzt, welche auch im späteren Verlauf verändert werden können.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Wizard", "Grundeinstellungen"))
        self.label_2.setToolTip(_translate("Wizard", "Opens the downloaded files with the default applications set in the OS"))
        self.label_2.setText(_translate("Wizard", "Default Apps"))
        self.label_3.setToolTip(_translate("Wizard", "Path where the downloaded files are stored. Defaults to ~/Desktop/SemapFiles"))
        self.label_3.setText(_translate("Wizard", "Save Path"))
        self.save_path.setPlaceholderText(_translate("Wizard", "~/Desktop/SemapFiles"))
        self.btn_save_path_select.setText(_translate("Wizard", "..."))
