# Generic, formatter-friendly config.
select = ["B", "D3", "D4", "E", "F"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
ignore = ["E501","F401"]
exclude = [
    ".trunk",
    ".git",
    ".github",
    "build",
    "dist",
    "docs",
    "examples",
    "tests",
    ".history",
    ".vscode",
    "venv",
    ".venv",
    "__pycache__",
]
line-length = 88
indent-width = 4
target-version = "py312"
[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
