# Form implementation generated from reading ui file 'ui/dialogs/extend_apparat.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(317, 126)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(60, 20, 231, 16))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(Frame)
        self.buttonBox.setGeometry(QtCore.QRect(90, 90, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.sem_winter = QtWidgets.QRadioButton(Frame)
        self.sem_winter.setGeometry(QtCore.QRect(60, 40, 82, 17))
        self.sem_winter.setObjectName("sem_winter")
        self.sem_sommer = QtWidgets.QRadioButton(Frame)
        self.sem_sommer.setGeometry(QtCore.QRect(60, 60, 82, 17))
        self.sem_sommer.setObjectName("sem_sommer")
        self.sem_year = QtWidgets.QLineEdit(Frame)
        self.sem_year.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.sem_year.setObjectName("sem_year")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Bis wann soll der Apparat verlängert werden?"))
        self.sem_winter.setText(_translate("Frame", "Winter"))
        self.sem_sommer.setText(_translate("Frame", "Sommer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
