# Form implementation generated from reading ui file 'c:\Users\aky547\GitHub\Semesterapparate\ui\widgets\message_widget.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from src.backend.database import Database


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(295, 110)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 47, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(60, 0, 41, 20))
        self.lineEdit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 281, 66))
        self.textEdit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.textEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.hidden_id = QtWidgets.QLabel(Form)
        self.hidden_id.setGeometry(QtCore.QRect(140, 10, 47, 13))
        self.hidden_id.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.hidden_id.setObjectName("hidden_id")
        self.hidden_id.hide()
        self.delete = False
        self.pushButton.clicked.connect(self.delete_message)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.textEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Apparat:"))
        self.label_2.setText(_translate("Form", "Nachricht:"))
        self.pushButton.setText(_translate("Form", "Löschen"))
        self.hidden_id.setText(_translate("Form", "TextLabel"))

    def set_message(self, message: str, apparat: int, app_id: int):
        self.textEdit.setText(message)
        self.lineEdit.setText(str(apparat) if apparat else "Alle")
        self.hidden_id.setText(str(app_id))

    def delete_message(self):
        db = Database()
        print("deleting message")
        db.delete_message(self.hidden_id.text())
